# Generated by Django 2.1.5 on 2019-03-13 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20190312_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='bird',
            name='image',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
